### ISSUE TITLE
Error starting app on android when library added

### ISSUE THREAD

**Issue by andrewpmoore** [DwayneCoussement/flutter_geofence#11]
Since adding the geofence library I'm now getting the following issue:
I know from reading that there's a bug in play store libraries when using android 10 phones with specific versions of the libraries where they are expecting a method isAtLeastR which doesn't exist.
I'm just not sure what needs fixing in the library to get it working again as everything I've seen talks about     

`implementation 'com.google.android.gms:play-services-base:17.x.x'`

but that's not used directly in the library from what I can tell

```
2020-04-01 16:02:10.887 24846-24846/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mypossibleself.app, PID: 24846
    java.lang.NoSuchMethodError: No static method isAtLeastR()Z in class Landroidx/core/os/BuildCompat; or its super classes (declaration of 'androidx.core.os.BuildCompat' appears in /data/app/com.mypossibleself.app-nbX7H-Iz9I79VneNwqg3dg==/base.apk!classes2.dex)
        at com.google.android.gms.common.util.PlatformVersion.isAtLeastR(com.google.android.gms:play-services-basement@@17.2.1:21)
        at com.google.android.gms.common.api.GoogleApi.zaa(com.google.android.gms:play-services-base@@17.2.1:128)
        at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.2.1:41)
        at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.2.1:56)
        at com.google.android.gms.location.GeofencingClient.<init>(Unknown Source:8)
        at com.google.android.gms.location.LocationServices.getGeofencingClient(Unknown Source:2)
        at com.intivoto.geofence.GeofenceManager.<init>(GeofenceManager.kt:58)
        at com.intivoto.geofence.GeofencePlugin$Companion.startGeofencing(GeofencePlugin.kt:83)
        at com.intivoto.geofence.GeofencePlugin$onAttachedToActivity$1.onRequestPermissionsResult(GeofencePlugin.kt:31)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:612)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:356)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:509)
        at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:673)
        at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:481)

```

**Comment by andrewpmoore** [comment]
ok I got to the bottom of a way around this.
Into my /app/build.gradle file I've added the following:

```
    implementation("com.google.android.gms:play-services-base:17.0.0"){
        force = true
    }
```

it seems that the default in the project was 17.2.1 which causes the issue, downgrading the base fixed that.
